### PR TITLE
chore: publish typedoc generated API docs

### PR DESCRIPTION
**Pull request by yusefnapora**
This adds a `typedoc` npm script to the client package to generate API docs and also spruces up the doc comments a bit by adding `@link` tags and a bit of extra explanation in a few places.

Still needs:

- [x] a "release" action to publish the docs to their final destination when the client package is published

### CODE REVIEW

**Comment by yusefnapora** [comment]
Hmm... not sure why the GH action's aren't running. Will debug this afternoon - converting to draft PR for now.

**Comment by yusefnapora** [comment]
current output: https://bafybeigz5ymnlfexdbln7zwuoe4r2awgi4cw6a4fexub3c42bhrjlse2xe.ipfs.nftstorage.link/

**Comment by yusefnapora** [comment]
@francois-potato are we planning to automate the release process for the client npm package? That seems like a decent place to hook in the typedoc publish action. 

If we're not there yet, I can add a script to manually generate the docs and check them into a `gh-pages` branch, or we could just always publish on merge to `main` (if files in the client package have changed).

**Comment by yusefnapora** [comment]
Heads up that I added a `typedoc:publish` npm script that publishes the typedoc output to github pages. It's now up here: https://web3-storage.github.io/w3name/

I also hooked it into the main client `publish` script, so it should update the typedocs whenever you publish the npm package (assuming you have write access to the repo).

**Comment by joshJarr** [comment]
Hey @yusefnapora, nice work!
We do want to add the client to the automated release process, but for now we're manually releasing it using the `npm run publish` command - thanks for adding the typedoc publishing to this!

Happy to grant you permission to the npm package too if you like, do you have a npm user? 
 
 Thanks!

**Comment by yusefnapora** [comment]
Sweet, I'm `sefnap` on npm.

**Review by joshJarr — APPROVED** [review]

**Pull request merged**
